// @vitest-environment node
import { describe, expect, it } from "vitest";
import { cleanBytes } from "@/lib/metadata";
import {
  extractJpegScans,
  jpegWithBrokenIcc,
  jpegSegments,
  jpegWithApp11,
  jpegWithComment,
  jpegWithMixedExif,
  jpegWithMultipartJumbf,
  jpegWithMultipartIcc,
  jpegWithUnknownAppAiText,
  progressiveJpegWithMetadataBetweenScans,
  readJpegExifOrientation,
} from "@/tests/fixtures/images";

describe("strict lossless JPEG cleaning", () => {
  it("rejects a truncated JPEG instead of returning a prefix", () => {
    expect(() => cleanBytes(Uint8Array.of(0xff, 0xd8, 0xff, 0xe1, 0x00, 0x40))).toThrow(
      "JPEG truncado",
    );
  });

  it("preserves JPEG scan bytes while removing an AI comment", () => {
    const source = jpegWithComment("Generated by Midjourney");
    const result = cleanBytes(source.bytes);

    expect(extractJpegScans(result.cleaned)).toEqual(source.scan);
    expect(result.findings.some((finding) => finding.source === "JPEG · COM")).toBe(true);
    expect(result.qualityVerified).toBe(true);
    expect(result.pixelPayloadHash).toMatch(/^crc32:[0-9a-f]{8}:7$/);
    expect(result.outputExtension).toBe(".jpg");
  });

  it("parses and cleans metadata between progressive scans", () => {
    const source = progressiveJpegWithMetadataBetweenScans();
    const result = cleanBytes(source.bytes);

    expect(extractJpegScans(result.cleaned)).toEqual(source.scan);
    expect(result.findings).toHaveLength(1);
    expect(result.qualityVerified).toBe(true);
    expect(() => cleanBytes(result.cleaned)).not.toThrow();
  });

  it("preserves non-JUMBF APP11 and unknown APP segments even when they mention AI", () => {
    for (const source of [jpegWithApp11(false), jpegWithUnknownAppAiText()]) {
      const result = cleanBytes(source);
      expect(result.cleaned).toEqual(source);
      expect(result.findings).toHaveLength(0);
    }
  });

  it("removes APP11 only after positive JUMBF classification", () => {
    const source = jpegWithApp11(true);
    const result = cleanBytes(source);

    expect(jpegSegments(source, 0xeb)).toHaveLength(1);
    expect(jpegSegments(result.cleaned, 0xeb)).toHaveLength(0);
    expect(result.findings[0]?.category).toBe("C2PA / Content Credentials");
    expect(extractJpegScans(result.cleaned)).toEqual(extractJpegScans(source));
  });

  it("reconstructs multipart APP11 before classifying and removing JUMBF", () => {
    const source = jpegWithMultipartJumbf();
    const result = cleanBytes(source);

    expect(jpegSegments(source, 0xeb)).toHaveLength(2);
    expect(jpegSegments(result.cleaned, 0xeb)).toHaveLength(0);
    expect(result.qualityVerified).toBe(true);
  });

  it("preserves all multipart ICC segments byte-for-byte", () => {
    const source = jpegWithMultipartIcc();
    const result = cleanBytes(source);

    expect(jpegSegments(result.cleaned, 0xe2)).toEqual(jpegSegments(source, 0xe2));
    expect(result.preserved.some((item) => item.label.includes("ICC"))).toBe(true);
  });

  it("redacts safe EXIF AI values without changing orientation", () => {
    const source = jpegWithMixedExif();
    const result = cleanBytes(source);
    const before = jpegSegments(source, 0xe1)[0];
    const after = jpegSegments(result.cleaned, 0xe1)[0];

    expect(after).not.toEqual(before);
    expect(after).toContain(6);
    expect(new TextDecoder().decode(after)).not.toContain("Midjourney");
    expect(result.qualityVerified).toBe(true);
  });

  it("preserves every LE and BE EXIF orientation value from 1 through 8", () => {
    for (const byteOrder of ["II", "MM"] as const) {
      for (let orientation = 1; orientation <= 8; orientation += 1) {
        const result = cleanBytes(jpegWithMixedExif(false, byteOrder, orientation));
        expect(readJpegExifOrientation(result.cleaned)).toBe(orientation);
      }
    }
  });

  it("rejects cyclic, aliased, and overlapping EXIF instead of dropping presentation data", () => {
    for (const kind of ["cycle", "alias", "overlap"] as const) {
      expect(() => cleanBytes(jpegWithMixedExif(kind))).toThrow(
        "EXIF no se puede limpiar de forma segura",
      );
    }
  });

  it("rejects JPEGs without a complete scan and EOI", () => {
    const source = jpegWithComment("ordinary comment");
    expect(() => cleanBytes(source.bytes.slice(0, -2))).toThrow("JPEG truncado");
    expect(() => cleanBytes(Uint8Array.of(0xff, 0xd8, 0xff, 0xd9))).toThrow(
      "JPEG sin datos de imagen",
    );
  });

  it("rejects invalid segment lengths, truncated SOS, and EOF after an entropy marker prefix", () => {
    const source = jpegWithComment("ordinary comment").bytes;
    for (const length of [0, 1]) {
      const malformed = source.slice();
      malformed[4] = 0;
      malformed[5] = length;
      expect(() => cleanBytes(malformed)).toThrow("Longitud JPEG inválida");
    }

    const sosOffset = source.findIndex((byte, index) => byte === 0xff && source[index + 1] === 0xda);
    expect(() => cleanBytes(source.slice(0, sosOffset + 5))).toThrow("JPEG truncado");

    const dangling = new Uint8Array(source.length - 1);
    dangling.set(source.slice(0, -2));
    dangling[dangling.length - 1] = 0xff;
    expect(() => cleanBytes(dangling)).toThrow("JPEG truncado");
  });

  it("rejects incomplete or duplicate multipart ICC sequences", () => {
    for (const kind of ["missing", "duplicate"] as const) {
      expect(() => cleanBytes(jpegWithBrokenIcc(kind))).toThrow("Secuencia ICC JPEG inválida");
    }
  });
});
