import type { FindingCategory } from "./types";

export interface AiSignature {
  re: RegExp;
  category: FindingCategory;
  label: string;
}

/**
 * Firmas de IA buscadas (case-insensitive) en texto extraído de los metadatos.
 * El orden importa solo para el etiquetado del primer match por firma.
 *
 * Nota: detectar es barato y eliminar estas etiquetas NUNCA afecta la calidad
 * (ICC, resolución, orientación y píxeles viven en otros segmentos), así que
 * preferimos cobertura amplia frente a falsos negativos.
 */
export const AI_SIGNATURES: AiSignature[] = [
  // ── Estándares de procedencia / Content Credentials ───────────────────────
  { re: /\bc2pa\b/i, category: "C2PA / Content Credentials", label: "Manifiesto C2PA" },
  { re: /content[\s_-]?credentials?/i, category: "C2PA / Content Credentials", label: "Content Credentials" },
  { re: /contentauth(?:enticity)?/i, category: "C2PA / Content Credentials", label: "Content Authenticity Initiative" },
  { re: /coalition for content provenance/i, category: "C2PA / Content Credentials", label: "C2PA (CAI)" },
  { re: /\bjumbf\b/i, category: "C2PA / Content Credentials", label: "Contenedor JUMBF" },
  { re: /claim[_\s-]?generator/i, category: "C2PA / Content Credentials", label: "C2PA claim_generator" },
  { re: /dcterms:provenance/i, category: "Provenance / XMP", label: "XMP dcterms:provenance" },
  { re: /digitalsourcetype/i, category: "Provenance / XMP", label: "IPTC DigitalSourceType" },
  { re: /trained[\s_]?algorithmic[\s_]?media/i, category: "Provenance / XMP", label: "Origen: medio algorítmico entrenado" },
  { re: /composite[\s_]?synthetic/i, category: "Provenance / XMP", label: "Origen: sintético compuesto" },
  { re: /algorithmic[\s_]?media/i, category: "Provenance / XMP", label: "Origen: medio algorítmico" },
  { re: /iptc4xmpext/i, category: "Provenance / XMP", label: "Extensión IPTC (procedencia)" },
  { re: /synthid/i, category: "Provenance / XMP", label: "Referencia a SynthID" },
  { re: /\bai[\s_-]?generated\b/i, category: "Marcador genérico de IA", label: "Marca \"AI generated\"" },
  { re: /generated\s+(?:by|with|using)\s+ai/i, category: "Marcador genérico de IA", label: "Marca \"generated by AI\"" },
  { re: /made\s+with\s+ai/i, category: "Marcador genérico de IA", label: "Marca \"made with AI\"" },
  { re: /generative\s*ai/i, category: "Marcador genérico de IA", label: "Marca \"Generative AI\"" },

  // ── Generadores de imagen ─────────────────────────────────────────────────
  { re: /midjourney/i, category: "Generador de IA", label: "Midjourney" },
  { re: /dall[\s._·•-]?e/i, category: "Generador de IA", label: "DALL·E" },
  { re: /\bopenai\b/i, category: "Generador de IA", label: "OpenAI" },
  { re: /gpt[\s-]?(?:4o|image|4\.1)/i, category: "Generador de IA", label: "OpenAI GPT Image" },
  { re: /(?:adobe\s+)?firefly/i, category: "Generador de IA", label: "Adobe Firefly" },
  { re: /generative\s+(?:fill|expand|remove)/i, category: "Generador de IA", label: "Photoshop · Relleno generativo" },
  { re: /stable\s*diffusion/i, category: "Generador de IA", label: "Stable Diffusion" },
  { re: /stability\.?ai/i, category: "Generador de IA", label: "Stability AI" },
  { re: /comfyui/i, category: "Generador de IA", label: "ComfyUI" },
  { re: /automatic1111/i, category: "Generador de IA", label: "AUTOMATIC1111" },
  { re: /invoke\s*ai/i, category: "Generador de IA", label: "InvokeAI" },
  { re: /novel\s*ai/i, category: "Generador de IA", label: "NovelAI" },
  { re: /leonardo\.?\s*ai/i, category: "Generador de IA", label: "Leonardo.Ai" },
  { re: /ideogram/i, category: "Generador de IA", label: "Ideogram" },
  { re: /black\s*forest\s*labs|\bflux\.?1?\b/i, category: "Generador de IA", label: "FLUX (Black Forest Labs)" },
  { re: /runway\s*ml|runwayml/i, category: "Generador de IA", label: "Runway" },
  { re: /luma\s*labs|lumalabs/i, category: "Generador de IA", label: "Luma" },
  { re: /recraft/i, category: "Generador de IA", label: "Recraft" },
  { re: /playground\s*ai|playgroundai/i, category: "Generador de IA", label: "Playground AI" },
  { re: /bing\s*image\s*creator/i, category: "Generador de IA", label: "Bing Image Creator" },
  { re: /microsoft\s*designer/i, category: "Generador de IA", label: "Microsoft Designer" },
  { re: /craiyon/i, category: "Generador de IA", label: "Craiyon" },
  { re: /nightcafe/i, category: "Generador de IA", label: "NightCafe" },
  { re: /\bwombo\b|dream\s*by\s*wombo/i, category: "Generador de IA", label: "WOMBO Dream" },
  { re: /\bgemini\b/i, category: "Generador de IA", label: "Google Gemini" },
  { re: /google\s+imagen|\bimagen[\s-]?[0-9]/i, category: "Generador de IA", label: "Google Imagen" },
  { re: /nano[\s-]?banana/i, category: "Generador de IA", label: "Nano Banana (Gemini)" },
  { re: /\bgrok\b/i, category: "Generador de IA", label: "Grok (xAI)" },
  { re: /seedream|seededit/i, category: "Generador de IA", label: "Seedream" },
  { re: /kling\s*ai|klingai/i, category: "Generador de IA", label: "Kling AI" },
  { re: /hailuo/i, category: "Generador de IA", label: "Hailuo" },
  { re: /qwen[\s-]?image/i, category: "Generador de IA", label: "Qwen-Image" },
  { re: /magnific/i, category: "Generador de IA", label: "Magnific" },
  { re: /\bkrea\b/i, category: "Generador de IA", label: "Krea" },
  { re: /freepik/i, category: "Generador de IA", label: "Freepik AI" },
  { re: /\bsora\b/i, category: "Generador de IA", label: "OpenAI Sora" },

  // ── Parámetros de generación (típicos de SD / ComfyUI / NovelAI) ──────────
  { re: /negative\s*prompt/i, category: "Datos de generación", label: "Prompt negativo" },
  { re: /\bsteps:\s*\d/i, category: "Datos de generación", label: "Pasos de muestreo" },
  { re: /\bsampler:/i, category: "Datos de generación", label: "Sampler" },
  { re: /cfg\s*scale/i, category: "Datos de generación", label: "CFG scale" },
  { re: /\bseed:\s*\d/i, category: "Datos de generación", label: "Seed" },
  { re: /model\s*hash/i, category: "Datos de generación", label: "Hash del modelo" },
  { re: /denoising\s*strength/i, category: "Datos de generación", label: "Denoising strength" },
  { re: /\bsd-metadata\b/i, category: "Datos de generación", label: "sd-metadata" },
  { re: /"class_type"/i, category: "Datos de generación", label: "Workflow ComfyUI" },
];

export interface SignatureHit {
  category: FindingCategory;
  label: string;
  match: string;
}

/** Devuelve todas las firmas que aparecen en el texto (una por firma, sin duplicar etiquetas). */
export function scanForAi(text: string): SignatureHit[] {
  if (!text) return [];
  const hits: SignatureHit[] = [];
  const seen = new Set<string>();
  for (const sig of AI_SIGNATURES) {
    const m = sig.re.exec(text);
    if (m && !seen.has(sig.label)) {
      seen.add(sig.label);
      hits.push({ category: sig.category, label: sig.label, match: m[0] });
    }
  }
  return hits;
}

/** ¿Hay algún rastro de IA en este texto? (rápido, corta en el primer match). */
export function hasAi(text: string): boolean {
  if (!text) return false;
  return AI_SIGNATURES.some((s) => s.re.test(text));
}

/**
 * Claves de chunks de texto PNG que, por sí solas, delatan datos de generación
 * (aunque el valor venga comprimido y no podamos inspeccionarlo).
 */
export const AI_PNG_TEXT_KEYWORDS = new Set(
  [
    "parameters",
    "prompt",
    "workflow",
    "sd-metadata",
    "generation_data",
    "dream",
    "comfyui",
    "invokeai_metadata",
    "invokeai_graph",
    "aigc",
  ].map((k) => k.toLowerCase()),
);
