import pako from "pako";

const encoder = new TextEncoder();
type FixtureBytes = Uint8Array<ArrayBufferLike>;

function concat(...parts: FixtureBytes[]): Uint8Array<ArrayBuffer> {
  const result = new Uint8Array(parts.reduce((total, part) => total + part.length, 0));
  let offset = 0;
  for (const part of parts) {
    result.set(part, offset);
    offset += part.length;
  }
  return result;
}

function u16(value: number): Uint8Array {
  return Uint8Array.of((value >>> 8) & 0xff, value & 0xff);
}

function u32(value: number): Uint8Array {
  return Uint8Array.of(
    (value >>> 24) & 0xff,
    (value >>> 16) & 0xff,
    (value >>> 8) & 0xff,
    value & 0xff,
  );
}

function u16le(value: number): Uint8Array {
  return Uint8Array.of(value & 0xff, (value >>> 8) & 0xff);
}

function u32le(value: number): Uint8Array {
  return Uint8Array.of(
    value & 0xff,
    (value >>> 8) & 0xff,
    (value >>> 16) & 0xff,
    (value >>> 24) & 0xff,
  );
}

function ascii(value: string): Uint8Array {
  return encoder.encode(value);
}

function jpegSegment(marker: number, payload: Uint8Array): Uint8Array {
  return concat(Uint8Array.of(0xff, marker), u16(payload.length + 2), payload);
}

const SOI = Uint8Array.of(0xff, 0xd8);
const EOI = Uint8Array.of(0xff, 0xd9);
const JFIF = jpegSegment(
  0xe0,
  concat(ascii("JFIF\0"), Uint8Array.of(1, 2, 1), u16(300), u16(300), Uint8Array.of(0, 0)),
);
const DQT = jpegSegment(0xdb, Uint8Array.of(0, ...new Array(64).fill(1)));
const DHT = jpegSegment(0xc4, Uint8Array.of(0, ...new Array(16).fill(0)));

function sof(marker = 0xc0, height = 1): Uint8Array {
  return jpegSegment(marker, concat(Uint8Array.of(8), u16(height), u16(1), Uint8Array.of(1, 1, 0x11, 0)));
}

function sos(spectralStart = 0, spectralEnd = 63): Uint8Array {
  return jpegSegment(
    0xda,
    Uint8Array.of(1, 1, 0, spectralStart, spectralEnd, 0),
  );
}

const BASE_SCAN = Uint8Array.of(0x2a, 0xff, 0x00, 0x91, 0xff, 0xd0, 0x33);

function jpegDocument(
  metadata: Uint8Array[] = [],
  scan = BASE_SCAN,
  frameMarker = 0xc0,
): Uint8Array {
  return concat(SOI, JFIF, ...metadata, DQT, sof(frameMarker), DHT, sos(), scan, EOI);
}

export function jpegWithComment(comment: string) {
  const scan = BASE_SCAN.slice();
  return {
    bytes: jpegDocument([jpegSegment(0xfe, ascii(comment))], scan),
    scan: [scan],
  };
}

export function progressiveJpegWithMetadataBetweenScans() {
  const first = Uint8Array.of(0x10, 0xff, 0x00, 0x20);
  const second = Uint8Array.of(0x30, 0xff, 0xd1, 0x40);
  const between = jpegSegment(0xfe, ascii("Generated by Midjourney"));
  return {
    bytes: concat(
      SOI,
      JFIF,
      DQT,
      sof(0xc2),
      DHT,
      sos(0, 0),
      first,
      between,
      DHT,
      sos(1, 63),
      second,
      EOI,
    ),
    scan: [first, second],
  };
}

const C2PA_UUID = Uint8Array.of(
  0x63, 0x32, 0x70, 0x61, 0x00, 0x11, 0x00, 0x10,
  0x80, 0x00, 0x00, 0xaa, 0x00, 0x38, 0x9b, 0x71,
);

function isoBox(type: string, payload: Uint8Array): Uint8Array {
  return concat(u32(8 + payload.length), ascii(type), payload);
}

function identifiedJumbf(uuid: Uint8Array, label: string): Uint8Array {
  const description = isoBox(
    "jumd",
    concat(uuid, Uint8Array.of(0x03), ascii(`${label}\0`)),
  );
  return isoBox("jumb", concat(description, isoBox("json", ascii("{}"))));
}

function c2paJumbf(): Uint8Array {
  return identifiedJumbf(C2PA_UUID, "c2pa");
}

export function jpegWithApp11(jumbf: boolean): Uint8Array {
  const payload = jumbf
    ? concat(ascii("JP"), u16(1), u32(1), c2paJumbf())
    : ascii("ordinary APP11 payload mentioning Midjourney but not JUMBF");
  return jpegDocument([jpegSegment(0xeb, payload)]);
}

export function jpegWithJumbfTrailingBytes(multipart: boolean): Uint8Array {
  const box = c2paJumbf();
  const framedWithGarbage = concat(box, Uint8Array.of(0xde, 0xad));
  if (!multipart) return jpegDocument([jpegSegment(0xeb, framedWithGarbage)]);
  const split = 11;
  return jpegDocument([
    jpegSegment(0xeb, concat(ascii("JP"), u16(9), u32(1), framedWithGarbage.slice(0, split))),
    jpegSegment(0xeb, concat(ascii("JP"), u16(9), u32(2), framedWithGarbage.slice(split))),
  ]);
}

export function jpegWithMultipartJumbf(): Uint8Array {
  const box = c2paJumbf();
  const split = 13;
  return jpegDocument([
    jpegSegment(0xeb, concat(ascii("JP"), u16(7), u32(1), box.slice(0, split))),
    jpegSegment(0xeb, concat(ascii("JP"), u16(7), u32(2), box.slice(split))),
  ]);
}

export function jpegWithNonC2paJumbf(
  multipart: boolean,
  description: "none" | "wrong-uuid" | "wrong-label" = "wrong-uuid",
): Uint8Array {
  const genericUuid = Uint8Array.of(
    0x10, 0x32, 0x54, 0x76, 0x98, 0xba, 0xdc, 0xfe,
    0x01, 0x23, 0x45, 0x67, 0x89, 0xab, 0xcd, 0xef,
  );
  const box =
    description === "none"
      ? isoBox("jumb", isoBox("json", ascii("{\"kind\":\"not-c2pa\"}")))
      : identifiedJumbf(
          description === "wrong-uuid" ? genericUuid : C2PA_UUID,
          description === "wrong-label" ? "not-c2pa" : "c2pa",
        );
  if (!multipart) return jpegDocument([jpegSegment(0xeb, box)]);
  const split = Math.floor(box.length / 2);
  return jpegDocument([
    jpegSegment(0xeb, concat(ascii("JP"), u16(12), u32(1), box.slice(0, split))),
    jpegSegment(0xeb, concat(ascii("JP"), u16(12), u32(2), box.slice(split))),
  ]);
}

const XMP_HEADER = "http://ns.adobe.com/xap/1.0/\0";
const EXTENDED_XMP_HEADER = "http://ns.adobe.com/xmp/extension/\0";

function standardXmp(xml: string): Uint8Array {
  return jpegSegment(0xe1, concat(ascii(XMP_HEADER), ascii(xml)));
}

export function jpegWithStandardXmp(kind: "safe-ai" | "mixed" | "presentation"): Uint8Array {
  const ai = kind === "presentation" ? "" : "<xmp:CreatorTool>Midjourney</xmp:CreatorTool>";
  const presentation =
    kind === "safe-ai"
      ? ""
      : ' tiff:Orientation="6" crs:CropTop="0.125" crs:Exposure2012="0.40"';
  const xml =
    `<x:xmpmeta xmlns:x="adobe:ns:meta/">` +
    `<rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">` +
    `<rdf:Description${presentation}>${ai}</rdf:Description>` +
    `</rdf:RDF></x:xmpmeta>`;
  return jpegDocument([standardXmp(xml)]);
}

export function jpegWithExtendedXmp(incomplete = false): Uint8Array {
  const guid = "0123456789ABCDEF0123456789ABCDEF";
  const extended = ascii(
    `<rdf:RDF><rdf:Description><xmp:CreatorTool>Midjourney</xmp:CreatorTool>` +
      `<crs:CropLeft>0.1</crs:CropLeft></rdf:Description></rdf:RDF>`,
  );
  const split = Math.min(100, extended.length - 1);
  const fragment = (offset: number, data: Uint8Array) =>
    jpegSegment(
      0xe1,
      concat(ascii(EXTENDED_XMP_HEADER), ascii(guid), u32(extended.length), u32(offset), data),
    );
  const main = standardXmp(
    `<x:xmpmeta><rdf:RDF><rdf:Description xmpNote:HasExtendedXMP="${guid}"/>` +
      `</rdf:RDF></x:xmpmeta>`,
  );
  const chunks = [fragment(0, extended.slice(0, split))];
  if (!incomplete) chunks.push(fragment(split, extended.slice(split)));
  return jpegDocument([main, ...chunks]);
}

export function jpegWithUnknownAppAiText(): Uint8Array {
  return jpegDocument([jpegSegment(0xe5, ascii("Midjourney private application data"))]);
}

export function jpegWithRepeatedMarkerFill(): Uint8Array {
  const source = jpegWithComment("ordinary comment").bytes;
  const marker = source.findIndex(
    (value, index) => value === 0xff && source[index + 1] === 0xfe,
  );
  return concat(source.slice(0, marker), Uint8Array.of(0xff), source.slice(marker));
}

export function jpegWithMultipartIcc(): Uint8Array {
  const first = jpegSegment(
    0xe2,
    concat(ascii("ICC_PROFILE\0"), Uint8Array.of(1, 2), ascii("profile-part-one")),
  );
  const second = jpegSegment(
    0xe2,
    concat(ascii("ICC_PROFILE\0"), Uint8Array.of(2, 2), ascii("profile-part-two")),
  );
  return jpegDocument([first, second]);
}

type ExifByteOrder = "II" | "MM";

function exifTiff(
  unsafe: "none" | "alias" | "overlap" | "cycle" | "unknown-alias",
  byteOrder: ExifByteOrder,
  orientationValue: number,
): Uint8Array {
  const software = ascii("Midjourney\0");
  const unsafeReference = unsafe === "alias" || unsafe === "overlap" || unsafe === "unknown-alias";
  const entryCount = unsafeReference ? 3 : 2;
  const ifdSize = 2 + entryCount * 12 + 4;
  const dataOffset = 8 + ifdSize;
  const write16 = byteOrder === "II" ? u16le : u16;
  const write32 = byteOrder === "II" ? u32le : u32;
  const orientation = concat(write16(0x0112), write16(3), write32(1), write16(orientationValue), Uint8Array.of(0, 0));
  const softwareEntry = concat(
    write16(0x0131),
    write16(2),
    write32(software.length),
    write32(dataOffset),
  );
  const entries = [orientation, softwareEntry];
  if (unsafeReference) {
    entries.push(
      unsafe === "unknown-alias"
        ? concat(write16(0xc001), write16(99), write32(software.length), write32(dataOffset))
        : concat(
            write16(0x011a),
            write16(5),
            write32(1),
            write32(unsafe === "alias" ? dataOffset : dataOffset + 2),
          ),
    );
  }
  return concat(
    ascii(byteOrder),
    write16(42),
    write32(8),
    write16(entryCount),
    ...entries,
    write32(unsafe === "cycle" ? 8 : 0),
    software,
  );
}

export function jpegWithMixedExif(
  unsafe: boolean | "alias" | "overlap" | "cycle" | "unknown-alias" = false,
  byteOrder: ExifByteOrder = "II",
  orientation = 6,
): Uint8Array {
  const unsafeMode = unsafe === true ? "alias" : unsafe === false ? "none" : unsafe;
  return jpegDocument([
    jpegSegment(0xe1, concat(ascii("Exif\0\0"), exifTiff(unsafeMode, byteOrder, orientation))),
  ]);
}

function littleEndianEntry(
  tag: number,
  type: number,
  count: number,
  valueOrOffset: number,
): Uint8Array {
  return concat(u16le(tag), u16le(type), u32le(count), u32le(valueOrOffset));
}

export function jpegWithIndirectExifAlias(kind: "thumbnail" | "strip"): Uint8Array {
  const software = ascii("Midjourney\0");
  const entryCount = 3;
  const dataOffset = 8 + 2 + entryCount * 12 + 4;
  const softwareEntry = littleEndianEntry(0x0131, 2, software.length, dataOffset);
  const offsetTag = kind === "thumbnail" ? 0x0201 : 0x0111;
  const lengthTag = kind === "thumbnail" ? 0x0202 : 0x0117;
  const tiff = concat(
    ascii("II"),
    u16le(42),
    u32le(8),
    u16le(entryCount),
    softwareEntry,
    littleEndianEntry(offsetTag, 4, 1, dataOffset),
    littleEndianEntry(lengthTag, 4, 1, software.length),
    u32le(0),
    software,
  );
  return jpegDocument([jpegSegment(0xe1, concat(ascii("Exif\0\0"), tiff))]);
}

export function jpegWithIfdTopologyOverlap(): Uint8Array {
  const preIfdData = concat(ascii("Midjourney\0"), new Uint8Array(13));
  const ifdOffset = 8 + preIfdData.length;
  const valueLength = 2 + 12 + 4 + preIfdData.length;
  const tiff = concat(
    ascii("II"),
    u16le(42),
    u32le(ifdOffset),
    preIfdData,
    u16le(1),
    littleEndianEntry(0x0131, 2, valueLength, 8),
    u32le(0),
  );
  return jpegDocument([jpegSegment(0xe1, concat(ascii("Exif\0\0"), tiff))]);
}

export function readJpegExifOrientation(bytes: Uint8Array): number {
  const segment = jpegSegments(bytes, 0xe1)[0];
  const tiff = 10;
  const little = String.fromCharCode(segment[tiff], segment[tiff + 1]) === "II";
  const read16 = (offset: number) =>
    little
      ? segment[offset] | (segment[offset + 1] << 8)
      : (segment[offset] << 8) | segment[offset + 1];
  const read32 = (offset: number) =>
    little
      ? (segment[offset] |
          (segment[offset + 1] << 8) |
          (segment[offset + 2] << 16) |
          (segment[offset + 3] << 24)) >>>
        0
      : ((segment[offset] << 24) |
          (segment[offset + 1] << 16) |
          (segment[offset + 2] << 8) |
          segment[offset + 3]) >>>
        0;
  const ifd = tiff + read32(tiff + 4);
  const count = read16(ifd);
  for (let index = 0; index < count; index += 1) {
    const entry = ifd + 2 + index * 12;
    if (read16(entry) === 0x0112) return read16(entry + 8);
  }
  throw new Error("orientation missing");
}

export function jpegWithBrokenIcc(kind: "missing" | "duplicate"): Uint8Array {
  const sequence = kind === "duplicate" ? 1 : 1;
  const total = 2;
  const chunks = [
    jpegSegment(0xe2, concat(ascii("ICC_PROFILE\0"), Uint8Array.of(sequence, total), ascii("part-one"))),
  ];
  if (kind === "duplicate") {
    chunks.push(
      jpegSegment(0xe2, concat(ascii("ICC_PROFILE\0"), Uint8Array.of(1, total), ascii("duplicate"))),
    );
  }
  return jpegDocument(chunks);
}

export function jpegWithDnl(
  kind: "valid" | "missing" | "zero" | "bad-length" | "before-sos",
): Uint8Array {
  const dnl =
    kind === "bad-length"
      ? jpegSegment(0xdc, Uint8Array.of(0, 1, 0))
      : jpegSegment(0xdc, u16(kind === "zero" ? 0 : 1));
  const prefix = [SOI, JFIF, DQT, sof(0xc0, 0), DHT];
  if (kind === "before-sos") return concat(...prefix, dnl, sos(), BASE_SCAN, EOI);
  if (kind === "missing") return concat(...prefix, sos(), BASE_SCAN, EOI);
  return concat(...prefix, sos(), BASE_SCAN, dnl, EOI);
}

export function extractJpegScans(bytes: Uint8Array): Uint8Array[] {
  const scans: Uint8Array[] = [];
  let offset = 2;
  while (offset < bytes.length) {
    if (bytes[offset] !== 0xff) throw new Error("fixture JPEG inválido");
    let codeOffset = offset + 1;
    while (bytes[codeOffset] === 0xff) codeOffset += 1;
    const marker = bytes[codeOffset];
    if (marker === 0xd9) return scans;
    if (marker === 0x01 || (marker >= 0xd0 && marker <= 0xd7)) {
      offset = codeOffset + 1;
      continue;
    }
    const length = (bytes[codeOffset + 1] << 8) | bytes[codeOffset + 2];
    const segmentEnd = codeOffset + 1 + length;
    if (marker !== 0xda) {
      offset = segmentEnd;
      continue;
    }
    let cursor = segmentEnd;
    while (cursor < bytes.length) {
      if (bytes[cursor] !== 0xff) {
        cursor += 1;
        continue;
      }
      let next = cursor + 1;
      while (bytes[next] === 0xff) next += 1;
      const nextMarker = bytes[next];
      if (nextMarker === 0 || (nextMarker >= 0xd0 && nextMarker <= 0xd7)) {
        cursor = next + 1;
        continue;
      }
      scans.push(bytes.slice(segmentEnd, cursor));
      offset = cursor;
      break;
    }
  }
  throw new Error("fixture JPEG sin EOI");
}

export function jpegSegments(bytes: Uint8Array, marker: number): Uint8Array[] {
  const found: Uint8Array[] = [];
  let offset = 2;
  while (offset + 1 < bytes.length) {
    if (bytes[offset] !== 0xff) break;
    const code = bytes[offset + 1];
    if (code === 0xd9 || code === 0xda) break;
    const length = (bytes[offset + 2] << 8) | bytes[offset + 3];
    const end = offset + 2 + length;
    if (code === marker) found.push(bytes.slice(offset, end));
    offset = end;
  }
  return found;
}

export const PNG_SIGNATURE = Uint8Array.of(0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a);

function fixtureCrc32(bytes: FixtureBytes): number {
  let crc = 0xffffffff;
  for (const byte of bytes) {
    crc ^= byte;
    for (let bit = 0; bit < 8; bit += 1) {
      crc = (crc >>> 1) ^ (crc & 1 ? 0xedb88320 : 0);
    }
  }
  return (crc ^ 0xffffffff) >>> 0;
}

export function pngChunk(type: string, data: FixtureBytes = new Uint8Array()): Uint8Array {
  const typeBytes = ascii(type);
  const body = concat(typeBytes, data);
  return concat(u32(data.length), body, u32(fixtureCrc32(body)));
}

const IHDR = pngChunk(
  "IHDR",
  concat(u32(1), u32(1), Uint8Array.of(8, 6, 0, 0, 0)),
);
const IDAT_DATA = Uint8Array.of(0x78, 0x9c, 0x63, 0x60, 0x60, 0x60, 0x00, 0x00, 0x00, 0x04, 0x00, 0x01);
const IDAT = pngChunk("IDAT", IDAT_DATA);
const IEND = pngChunk("IEND");

export function pngDocument(chunks: FixtureBytes[] = []): Uint8Array {
  return concat(PNG_SIGNATURE, IHDR, ...chunks, IDAT, IEND);
}

export function pngWithText(keyword: string, text: string): Uint8Array {
  return pngDocument([pngChunk("tEXt", concat(ascii(keyword), Uint8Array.of(0), ascii(text)))]);
}

export function pngWithCompressedText(size: number): Uint8Array {
  const expanded = ascii(`Steps: 30 ${"x".repeat(size)}`);
  const compressed = pako.deflate(expanded);
  return pngDocument([
    pngChunk("zTXt", concat(ascii("comment"), Uint8Array.of(0, 0), compressed)),
  ]);
}

export function pngWithCompressedInternationalText(size: number): Uint8Array {
  const expanded = ascii(`Steps: 30 ${"x".repeat(size)}`);
  return pngDocument([
    pngChunk(
      "iTXt",
      concat(
        ascii("comment"),
        Uint8Array.of(0, 1, 0, 0, 0),
        pako.deflate(expanded),
      ),
    ),
  ]);
}

export function pngWithMalformedText(
  type:
    | "ztxt-corrupt"
    | "ztxt-method"
    | "ztxt-separator"
    | "itxt-method"
    | "itxt-separator"
    | "ztxt-trailing"
    | "itxt-trailing"
    | "ztxt-concatenated",
): Uint8Array {
  if (type === "ztxt-corrupt") {
    return pngDocument([pngChunk("zTXt", concat(ascii("comment"), Uint8Array.of(0, 0, 1, 2, 3)))]);
  }
  if (type === "ztxt-method") {
    return pngDocument([pngChunk("zTXt", concat(ascii("comment"), Uint8Array.of(0, 1), pako.deflate(ascii("ok"))))]);
  }
  if (type === "ztxt-separator") {
    return pngDocument([pngChunk("zTXt", ascii("no separator"))]);
  }
  if (type === "ztxt-trailing" || type === "ztxt-concatenated") {
    const tail =
      type === "ztxt-trailing"
        ? Uint8Array.of(0xde, 0xad)
        : pako.deflate(ascii("second stream"));
    return pngDocument([
      pngChunk(
        "zTXt",
        concat(ascii("comment"), Uint8Array.of(0, 0), pako.deflate(ascii("first stream")), tail),
      ),
    ]);
  }
  if (type === "itxt-trailing") {
    return pngDocument([
      pngChunk(
        "iTXt",
        concat(
          ascii("comment"),
          Uint8Array.of(0, 1, 0, 0, 0),
          pako.deflate(ascii("first stream")),
          Uint8Array.of(0xde, 0xad),
        ),
      ),
    ]);
  }
  if (type === "itxt-method") {
    return pngDocument([
      pngChunk("iTXt", concat(ascii("comment"), Uint8Array.of(0, 1, 1, 0, 0), pako.deflate(ascii("ok")))),
    ]);
  }
  return pngDocument([pngChunk("iTXt", concat(ascii("comment"), Uint8Array.of(0, 1, 0)))]);
}

export function pngWithInvalidOrder(
  kind:
    | "duplicate-ihdr"
    | "plte-after-idat"
    | "noncontiguous-idat"
    | "missing-plte"
    | "trailing"
    | "color-after-plte"
    | "duplicate-phys"
    | "reserved-bit"
    | "apng-frame-count"
    | "plte-too-large"
    | "trns-before-plte"
    | "trns-with-alpha"
    | "invalid-gama-length"
    | "apng-frame-without-data"
    | "fdat-without-active-fctl"
    | "invalid-dispose-op"
    | "invalid-blend-op",
): Uint8Array {
  if (kind === "duplicate-ihdr") return concat(PNG_SIGNATURE, IHDR, IHDR, IDAT, IEND);
  if (kind === "plte-after-idat") {
    return concat(PNG_SIGNATURE, IHDR, IDAT, pngChunk("PLTE", Uint8Array.of(0, 0, 0)), IEND);
  }
  if (kind === "noncontiguous-idat") {
    return concat(
      PNG_SIGNATURE,
      IHDR,
      pngChunk("IDAT", Uint8Array.of(1)),
      pngChunk("tEXt", concat(ascii("comment"), Uint8Array.of(0), ascii("ok"))),
      pngChunk("IDAT", Uint8Array.of(2)),
      IEND,
    );
  }
  if (kind === "missing-plte") {
    const indexedHeader = pngChunk(
      "IHDR",
      concat(u32(1), u32(1), Uint8Array.of(8, 3, 0, 0, 0)),
    );
    return concat(PNG_SIGNATURE, indexedHeader, IDAT, IEND);
  }
  if (kind === "color-after-plte") {
    const indexedHeader = pngChunk(
      "IHDR",
      concat(u32(1), u32(1), Uint8Array.of(8, 3, 0, 0, 0)),
    );
    return concat(
      PNG_SIGNATURE,
      indexedHeader,
      pngChunk("PLTE", Uint8Array.of(0, 0, 0)),
      pngChunk("gAMA", u32(45455)),
      IDAT,
      IEND,
    );
  }
  if (kind === "duplicate-phys") {
    const phys = pngChunk("pHYs", concat(u32(1), u32(1), Uint8Array.of(1)));
    return concat(PNG_SIGNATURE, IHDR, phys, phys, IDAT, IEND);
  }
  if (kind === "reserved-bit") {
    return concat(PNG_SIGNATURE, IHDR, pngChunk("vpag", ascii("private")), IDAT, IEND);
  }
  if (kind === "apng-frame-count") {
    return concat(
      PNG_SIGNATURE,
      IHDR,
      pngChunk("acTL", concat(u32(2), u32(0))),
      pngChunk("fcTL", concat(u32(0), u32(1), u32(1), u32(0), u32(0), u16(1), u16(30), Uint8Array.of(0, 0))),
      IDAT,
      IEND,
    );
  }
  if (kind === "plte-too-large" || kind === "trns-before-plte") {
    const indexedHeader = pngChunk(
      "IHDR",
      concat(u32(1), u32(1), Uint8Array.of(1, 3, 0, 0, 0)),
    );
    const palette = pngChunk("PLTE", Uint8Array.of(0, 0, 0, 255, 255, 255, 12, 12, 12));
    return kind === "plte-too-large"
      ? concat(PNG_SIGNATURE, indexedHeader, palette, IDAT, IEND)
      : concat(PNG_SIGNATURE, indexedHeader, pngChunk("tRNS", Uint8Array.of(0)), palette, IDAT, IEND);
  }
  if (kind === "trns-with-alpha") {
    return concat(PNG_SIGNATURE, IHDR, pngChunk("tRNS", Uint8Array.of(0)), IDAT, IEND);
  }
  if (kind === "invalid-gama-length") {
    return concat(PNG_SIGNATURE, IHDR, pngChunk("gAMA", Uint8Array.of(1)), IDAT, IEND);
  }
  if (kind === "apng-frame-without-data") {
    return concat(
      PNG_SIGNATURE,
      IHDR,
      pngChunk("acTL", concat(u32(1), u32(0))),
      IDAT,
      pngChunk("fcTL", concat(u32(0), u32(1), u32(1), u32(0), u32(0), u16(1), u16(30), Uint8Array.of(0, 0))),
      IEND,
    );
  }
  if (kind === "fdat-without-active-fctl") {
    return concat(
      PNG_SIGNATURE,
      IHDR,
      pngChunk("acTL", concat(u32(1), u32(0))),
      pngChunk("fcTL", concat(u32(0), u32(1), u32(1), u32(0), u32(0), u16(1), u16(30), Uint8Array.of(0, 0))),
      IDAT,
      pngChunk("fdAT", concat(u32(1), Uint8Array.of(1, 2, 3))),
      IEND,
    );
  }
  if (kind === "invalid-dispose-op" || kind === "invalid-blend-op") {
    const operations = kind === "invalid-dispose-op" ? Uint8Array.of(3, 0) : Uint8Array.of(0, 2);
    return concat(
      PNG_SIGNATURE,
      IHDR,
      pngChunk("acTL", concat(u32(1), u32(0))),
      pngChunk("fcTL", concat(u32(0), u32(1), u32(1), u32(0), u32(0), u16(1), u16(30), operations)),
      IDAT,
      IEND,
    );
  }
  return concat(PNG_SIGNATURE, IHDR, IDAT, IEND, Uint8Array.of(1));
}

export function apngWithAiText() {
  const idat = Uint8Array.of(1, 2, 3, 4);
  const fdat = concat(u32(2), Uint8Array.of(5, 6, 7, 8));
  const bytes = concat(
    PNG_SIGNATURE,
    IHDR,
    pngChunk("acTL", concat(u32(2), u32(0))),
    pngChunk("fcTL", concat(u32(0), u32(1), u32(1), u32(0), u32(0), u16(1), u16(30), Uint8Array.of(0, 0))),
    pngChunk("IDAT", idat),
    pngChunk("tEXt", concat(ascii("parameters"), Uint8Array.of(0), ascii("Steps: 30"))),
    pngChunk("fcTL", concat(u32(1), u32(1), u32(1), u32(0), u32(0), u16(1), u16(30), Uint8Array.of(0, 0))),
    pngChunk("fdAT", fdat),
    IEND,
  );
  return { bytes, pixelPayloads: [idat, fdat] };
}

export function pngWithUnknownChunk(type: string, data: string): Uint8Array {
  return pngDocument([pngChunk(type, ascii(data))]);
}

export function pngWithC2pa(): Uint8Array {
  return pngDocument([pngChunk("caBX", ascii("c2pa manifest"))]);
}

export function pngWithColorAndDensity(): Uint8Array {
  return pngDocument([
    pngChunk("sRGB", Uint8Array.of(0)),
    pngChunk("gAMA", u32(45455)),
    pngChunk("pHYs", concat(u32(11811), u32(11811), Uint8Array.of(1))),
  ]);
}

export function pngWithHighBitField(kind: "chunk-length" | "width" | "height"): Uint8Array {
  if (kind === "chunk-length") {
    return concat(PNG_SIGNATURE, u32(0x80000000), ascii("IDAT"));
  }
  const header = pngChunk(
    "IHDR",
    concat(
      u32(kind === "width" ? 0x80000000 : 1),
      u32(kind === "height" ? 0x80000000 : 1),
      Uint8Array.of(8, 6, 0, 0, 0),
    ),
  );
  return concat(PNG_SIGNATURE, header, IDAT, IEND);
}

export function extractPngPayloads(bytes: Uint8Array): Uint8Array[] {
  const payloads: Uint8Array[] = [];
  let offset = 8;
  while (offset < bytes.length) {
    const length =
      ((bytes[offset] << 24) |
        (bytes[offset + 1] << 16) |
        (bytes[offset + 2] << 8) |
        bytes[offset + 3]) >>>
      0;
    const type = String.fromCharCode(...bytes.slice(offset + 4, offset + 8));
    if (type === "IDAT" || type === "fdAT") {
      payloads.push(bytes.slice(offset + 8, offset + 8 + length));
    }
    offset += 12 + length;
    if (type === "IEND") return payloads;
  }
  throw new Error("fixture PNG sin IEND");
}

export function pngChunks(bytes: Uint8Array, wantedType: string): Uint8Array[] {
  const chunks: Uint8Array[] = [];
  let offset = 8;
  while (offset < bytes.length) {
    const length =
      ((bytes[offset] << 24) |
        (bytes[offset + 1] << 16) |
        (bytes[offset + 2] << 8) |
        bytes[offset + 3]) >>>
      0;
    const type = String.fromCharCode(...bytes.slice(offset + 4, offset + 8));
    const end = offset + 12 + length;
    if (type === wantedType) chunks.push(bytes.slice(offset, end));
    offset = end;
    if (type === "IEND") break;
  }
  return chunks;
}
